### ISSUE TITLE
1.9 version

### ISSUE THREAD

**Issue by Feerko** [Europia79/VirtualPlayers#4]

**Comment by Europia79** [comment]
Here's the code changes:
https://github.com/Europia79/VirtualPlayers/commit/cac2c9e4cc9c9f240d1328eac51205955221512e

Here's the download:
http://rainbowcraft.sytes.net/download/plugins/VirtualPlayers2/v1.6.8/

**Comment by Feerko** [comment]
Excellently! Thank you very much. :)
Dnia 9 marca 2016 19:22 Europia79 &lt;notifications@github.com&gt; napisał(a):
Here&#39;s the code changes:
cac2c9eHere&#39;s the download:
http://rainbowcraft.sytes.net/download/plugins/VirtualPlayers2/v1.6.8/—
