### ISSUE TITLE
1.10 Version

### ISSUE THREAD

**Issue by Feerko** [Europia79/VirtualPlayers#5]
Hello!
Plugin does not work on version 1.10. Could you update it?
I really care. Thanks.

**Comment by Feerko** [comment]
Please, really care about it.

**Comment by Europia79** [comment]
i'm using Spigot's BuildTools to build v1.10 now... I'll probably do the VirtualPlayers update tomorrow.

it's really easy to update: You simply copy & paste the last folder which was ```/modules/v1_9_R2/```

When you paste it on Windows, the new folder will be ```/v1_9_R2 Copy```. Just rename the folder to ```/v1_10_R1```

Open the file ```/v1_10_R1/pom.xml``` and replace any occurrences of the old version ```v1_9_R2``` with the new version ```v1_10_R1```

Then add this new module to the root ```pom.xml```

Also, add the new module to ```/modules/VirtualPlayers/pom.xml```

The final step is to fix the compiler errors (which is pretty straight-forward) and build with Maven commands:

```
mvn clean build
```

**Comment by Europia79** [comment]
just uploaded it:

http://dev.bukkit.org/bukkit-plugins/virtualplayers2/
http://rainbowcraft.sytes.net/download/plugins/VirtualPlayers2/v1.7.2/

Look for v1.7.2 of VirtualPlayers
